spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prs}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    change-log: classpath:db/changelog/master.xml

auth-jwt:
  issuer: ${JWT_ISSUER}
  tokens:
    access:
      key: ${JWT_TOKENS_ACCESS_KEY}
      ttl-in-seconds: 1200
    refresh:
      key: ${JWT_TOKENS_REFRESH_KEY}
      ttl-in-seconds: 12000

encrypt:
  keys:
    accessToken_key: ${POSTGRESQL_ACCESS_TOKEN_KEY}
    refreshToken_key: ${POSTGRESQL_REFRESH_TOKEN_KEY}
    personalInfo_key: ${POSTGRESQL_PERSONAL_INFO_TOKEN_KEY}

logging:
  pattern:
    console: '%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger) - [%X] %msg%n'
  level:
    dev.rkashapov: trace

server:
  error:
    include-message: always
